### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by psprint** [exzombie/prll#4]
Could you provide examples, use cases? It's hard to imagine oneself how prll can be used.

**Comment by exzombie** [comment]
I was surprised at first, since there are many examples in the manual. But you are right, there should be some in the README. In fact, there were some on the old homepage, but I forgot about them when I migrated to Github. I will add some shortly, thanks for reminding me.

**Comment by exzombie** [comment]
Do you think 0e944dfe30eb457254cf63a26208fad3c6fb49d5 is sufficient?

**Comment by psprint** [comment]
Looks good and explains much. When I read README for the first time, I had impression that some complex shell interaction is possible. No worries, the use case you provided is cool, ability to use shell functions is of great importance. If I would look at README second time, I would probably get on the ground as it would be revealed that my impressions was mostly my imagination. That's why I'm not reading for second time to save the expectations. So my question is if there is some other trick possible? prll uses message queues and semaphores, can run functions, uses /dev/*random, does this yield some other use case?

**Comment by exzombie** [comment]
Hm, I'm not sure what you mean. The README doesn't contain much info anyway, the manual (`prll.txt`) is where you can get a better idea of what prll is. And what it _is_ is a tool, so yeah, what it can be used for is pretty much defined by your imagination :) . I only know what _I_ use it for, most of the time it's just running simple commands on a bunch of files, other times I write complex scripts to e.g. run molecular simulations and process the results. I have no idea what others use it for, except that I implemented `prll_interrupt` on request because someone was doing a parallel search.

**Comment by psprint** [comment]
I had impression of a swiss-knife property of prll. I dig into such projects, it's pretty fun. So I asked for possible different use case, some possible trick.

**Comment by exzombie** [comment]
Well, it doesn't have a wine-bottle opener ;) . But I do wish you a lot of fun poking at it!
